[project]
channels = ["conda-forge","robostack-humble"]
name = "roslibjs_demo"
platforms = ["linux-64","osx-64","win-64"]
version = "0.1.0"

[target.osx-64.tasks]
website="open https://nmarticorena.github.io/pixi-wasm"

[target.linux-64.tasks]
website = "detach xdg-open https://nmarticorena.github.io/pixi-wasm"

[target.win-64.tasks]
website = "start https://nmarticorena.github.io/pixi-wasm"

[tasks]
demo="ros2 launch example.launch.py"

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
ros-humble-rosbridge-server = ">=2.0.0,<3"
ros-humble-rosbridge-suite = ">=2.0.0,<3"
